### PR TITLE
Fixed deploy process.

### LINKED ISSUE #144: Deploying is adding/removing files that it shouldn't
Hey @tscanlin - everytime I run `npm run deploy`, it seems to add or remove a bunch of unrelated files to the ones that I change in my commits. The files that get added/removed don't really make any sense and are completely unrelated. Some of these diffs are +/- 1000 lines. Do you know why deploying to `gh-pages` adds or removes a huge amount of unrelated lines?

### PR DESCRIPTION
**Pull request by bhamodi**
Hey @tscanlin - I fixed the deploy process. This fixes #144 by running clean and build before doing a deploy. :+1:

### CODE REVIEW

**Comment by tscanlin** [comment]
We should probably make the gulp build/default tasks be the same or at least reference the same array, but I can do that later this weekend so don't worry about it.

**Comment by bhamodi** [comment]
Cool, the only difference is that the `default` gulp task has the added livereload and file watch features. The `build` gulp script only builds the files and doesn't boot up the local server.

**Comment by tscanlin** [comment]
oh, good point. I guess I just meant the default task could run the build task instead of listing them again. Eg:
```
gulp.task('default', [
  // 'markdown',
  'build',
  'browser-sync',
  'watch',
]);
```

**Comment by bhamodi** [comment]
Oooh nice optimization. Yeah I like that. :+1:

**Pull request merged**
