### PR TITLE
Tim/search

### PR DESCRIPTION
**Pull request by tscanlin**
@nchilada can you review this when you have a chance?

Also @danoc can you review since there are CSS changes?

This PR adds docsearch, docs are here:
https://community.algolia.com/docsearch/documentation/

### CODE REVIEW

**Comment by nchilada** [comment]
Wow, this is slick!  I like how the search engine prioritizes exact matches for any text that you enter, including for API function names, while also being able to return inexact matches.

I don't have any meaningful code complaints, but I do have a couple usability thoughts...

1. If you enter text that matches a heading, the search engine is able to link to the expected anchor on the expected page, but the matched text doesn't appear in the suggestion.  The only thing that appears is the name of the entire page that is being linked to.
  * How to reproduce: search for "getAttributeValue".  The suggestion reads "REST API" but does not include "getAttributeValue", although it correctly links to http://developers.optimizely.com/javascript/personalization/index.html#getAttributeValue.

2. It can be frustrating that we only return one link into any given page, since we document so many API functions on every page.
  * How to reproduce: search for "experiment results".  You'll see a suggestion that links to http://developers.optimizely.com/rest/code-samples/#results, but no suggestion that links to http://developers.optimizely.com/rest/reference/index.html#get-results.

**Comment by tscanlin** [comment]
@nikhil, thanks for the feedback. I totally agree with both of the issues that you brought up and I have noticed them too, although I'm not sure how much control we have to fix these things since they seem to be related to how docsearch works.

1. There is another field that I am hiding that shows the sub section text, however in most cases this just repeats the page name. See the 2 images below:
screen shot 2016-02-10 at 11 18 17 am

That shows the sub section for the "getAttributeValue" term, but it doesn't work so well for other search terms, see:
screen shot 2016-02-10 at 11 18 56 am


2. I've noticed this with other terms too where it doesn't find all the instances for certain sections. I'll try bringing this up to the Algolia team to see if they can fix it, but I think we will need to deploy this and iterate on it with their help to be able to properly diagnose and resolve the issue.

Great feedback @nchilada!!

**Comment by nchilada** [comment]
Yeah, iterating on this should be fine - I don't think the current implementation is going to make anyone's browsing experience _worse_.

LGTM!

**Comment by danoc** [comment]
Sorry I missed this one (was on vacation), but nice work Tim! I'd be curious to hear how you like Algolia. Seems slick.

**Comment by tscanlin** [comment]
No worries, thanks Dan! I was initially hesitant about Algolia, but after trying it and seeing how lightning fast their API is I am quite impressed. Definitely have a good impression of them so far.

Also, we may potentially use their product in other places like the marketing site, and maybe design-dot. Both those are both TBD and nothing has been decided yet. I'll let you know once I have better info about those decisions.

**Pull request merged**
