### PR TITLE
animate me some lines.

### PR DESCRIPTION
**Pull request by tscanlin**

### CODE REVIEW

**Comment by bhamodi** [comment]
LGTM.

**Comment by tscanlin** [comment]
@LindaHong not sure if you still have time for this or are caught up in other things now?

Do you think I should merge this in and you can tweak it in a subsequent PR or would you rather merge in your PR?

**Comment by LindaHong** [comment]
@tscanlin I can merge my PR if you don't mind.

**Comment by tscanlin** [comment]
@LindaHong sure, just tag me in the PR so I can review it first. Thanks!

**Comment by tscanlin** [comment]
Closing this in favor of:
https://github.com/optimizely/developers.optimizely.com/pull/110

**Pull request closed without merging**
