### PR TITLE
fix escaping

### PR DESCRIPTION
**Pull request by tscanlin**
Fixes escaping so `&quot;` doesn't appear.

### CODE REVIEW

**Comment by tscanlin** [comment]
@nchilada & @mauerbac this fixes: https://optimizely.atlassian.net/browse/DEV-428

**Comment by tscanlin** [comment]
I feel like this is high enough priority and low enough risk that I should just merge this. I have tested locally to confirm.

Thanks for letting me know about this bug @nchilada! :+1:

**Comment by nchilada** [comment]
Thanks @tscanlin!  Out of curiosity, do you know what the breaking change was?  I can't find anything suspect in the recent git history.

**Comment by tscanlin** [comment]
I think it was from when I switched templating engines. I bet the escaping was handled differently and I never noticed it before.

**Comment by nchilada** [comment]
Oh wow, that must be it.  I think I did some QA too; I must have used /javascript/reference instead of /rest/reference or /rest/customer-profiles.

**Pull request merged**
