### PR TITLE
Fixed bug for group mutually exclusive experiments

### PR DESCRIPTION
**Pull request by Bigspencey**
@tscanlin We'll have another slight fix to this later this week, but wanted to correct this now. The new code requires that group mutual exclusion is defined by "_me" rather than "me". This resolves a bug where group definitions are used in concert with a title where "me" is included in the string.

### CODE REVIEW

**Comment by tscanlin** [comment]
It's hard to see the change in this diff since the whole string is one line (not a bad thing, just the snippet's nature) but I trust it's all good, LGTM.

**Comment by bhamodi** [comment]
Changes seem fine here: https://www.diffchecker.com/cwqcjglq
@tscanlin - this is a nice tool for snippet pull requests. :)

**Comment by tscanlin** [comment]
Oh cool! Nice to know about that :+1:

**Comment by bhamodi** [comment]
Merging this in now @Bigspencey. Give @tscanlin a shout when the newer snippet is ready later this week.

**Pull request merged**
