### PR TITLE
Update UUID Disclaimers given recent investigation by Nikhil

### PR DESCRIPTION
**Pull request by chrix-optimizely**
Hey @nchilada @tscanlin can you guys take a quick peek at my updated UUID disclaimer? Once this is live I'll update the KB too.

### CODE REVIEW

**Comment by tscanlin** [comment]
LGTM. Thanks for the update Chrix!

**Comment by nchilada** [comment]
Maybe change

    We recommend that you use UUID only on projects where all visitors have a UUID

to

    We recommend that you use UUID only on projects where all experiments are targeted to visitors with UUIDs

since every project is likely to have non-UUID visitors at some point...

**Comment by chrix-optimizely** [comment]
Updated! cc @nchilada

**Comment by nchilada** [comment]
LGTM

**Pull request merged**
