### PR TITLE
Added http:// to redirect comment

### PR DESCRIPTION
**Pull request by harrisonkrat**
Added http:// to redirect comment

### CODE REVIEW

**Comment by harrisonkrat** [comment]
@tscanlin I've gone through all the required steps on this one, but after running npm run gulp I can't see my changes locally.  I've tried npm update, npm install, and npm run clean several times, still to no avail.

**Comment by harrisonkrat** [comment]
@tscanlin I was able to see the changes locally but couldn't deploy.  I didn't recognize the error; let me know if you have time to discuss in the next couple days.

**Comment by bhamodi** [comment]
Hey @harrisonkrat - I can help you with deploy issues too. In fact, I was about to deploy these changes for you. But then I looked at the diff and I'm wondering if these changes are changes that we want to actually deploy. I don't think adding `http://` before these variables makes sense because it doesn't represent an actual URL. I might be missing something, so could you explain to me what the reasoning for this change is? :)

**Comment by harrisonkrat** [comment]
Hi Baraa,

If you don't include _optimizely_redirect=http:// as the first part of the
comment, Optimizely won't recognize the code as a redirect and won't fire
that code at the proper step in our order of execution.  This could lead to
page flashing.  In addition, you can break the editor if you execute a
window.location change without the comment.  We call out this
consideration here
in our KB <https://help.optimizely.com/hc/en-us/articles/200040675#modify>,
but we omitted it in these code samples, so we're just trying to close that
gap.

Please let me know if you need any other details.  Thanks.


*Harrison Krat*
Solutions Architect | Optimizely, Inc. <http://www.optimizely.com/>
harrison@optimizely.com | O: 415-376-4536
-------------------------------------------------------------
Web <http://www.optimizely.com/> | LinkedIn
<http://www.linkedin.com/company/optimizely> | Twitter
<https://twitter.com/Optimizely> | Facebook
<http://www.facebook.com/optimizely>



Couldn't make it to #Opticon2015? Check out the highlights
<http://optimize.ly/1Lo1IkN> here!

**Comment by bhamodi** [comment]
Hey @harrisonkrat - thanks for the explanation. I just deployed for you! :+1: 
Please check to see if your desired changes are live.

Also, come by my desk later today and I'll help you setup your local environment. :)

**Comment by harrisonkrat** [comment]
Thanks Baraa, the changes look great on the live site!

I've got my local env set up and I've done a lot of debugging with Tim -
for whatever reason I can't go two times in a row with a clean end-to-end
process.

Are you free between 2 and 4 today?  Where do you sit?


*Harrison Krat*
Solutions Architect | Optimizely, Inc. <http://www.optimizely.com/>
harrison@optimizely.com | O: 415-376-4536
-------------------------------------------------------------
Web <http://www.optimizely.com/> | LinkedIn
<http://www.linkedin.com/company/optimizely> | Twitter
<https://twitter.com/Optimizely> | Facebook
<http://www.facebook.com/optimizely>



Couldn't make it to #Opticon2015? Check out the highlights
<http://optimize.ly/1Lo1IkN> here!

**Comment by bhamodi** [comment]
Yup, I'm free during those hours. I'll schedule something on your calendar. :+1:

**Comment by tscanlin** [comment]
Thanks for helping out Baraa, you're awesome! Let me know if you need help or if you get stuck debugging I think I'll be free between those hours too. I really appreciate it!! :)

**Comment by bhamodi** [comment]
Haha, no problem! #ownership

**Pull request merged**
