### PR TITLE
Use a nicer looking URL for OUI assets in Optimizely Apps documentation

### PR DESCRIPTION
**Pull request by danoc**
cc: @tscanlin, @jgaul

### CODE REVIEW

**Comment by tscanlin** [comment]
Omg, so much better!! :+1:

**Comment by tscanlin** [comment]
lgtm

**Comment by tscanlin** [comment]
although, shouldn't you not force https?

**Comment by danoc** [comment]
The protocol-relative URLs are now considered an anti-pattern!
http://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by tscanlin** [comment]
Good to know! Thanks for sharing that info. Feel free to merge away! :)

**Pull request merged**
