### PR TITLE
Document the `dcp.getAttributeValue` JavaScript API

### PR DESCRIPTION
**Pull request by nchilada**

### CODE REVIEW

**Comment by tscanlin** [comment]
What's the reasoning for switching everything to bold h5 headings? I don't think we use h5's too commonly on the dev docs.

**Comment by nchilada** [comment]
On that page, we currently use h4 headings for the name of each function as well as for the subsections for each functions.  I think we ought to use h5 for the subsections.

Unfortunately, h5 is so small that it's hard to distinguish from the actual text.  So we need to style those headings slightly differently.  Admittedly, making them bold via Markdown is a hack, as they ought to be styled using CSS, if at all.

FYI, the page is currently inconsistent: it uses h4 in most places, but it also uses bolded h5 here and there.

**Comment by tscanlin** [comment]
I see what you're saying. Since h5 is the exact same size as the body text, why make them h5 headings at all? I think it would make more sense to keep them bold but just make them spans or p tags.

**Comment by nchilada** [comment]
h5 seemed semantically appropriate, and more straightforward to style in the future.  But I can change to span or p if you so prefer.

**Comment by tscanlin** [comment]
I'm fine either way, I'll let you make the call. LGTM

**Comment by nchilada** [comment]
Okay, thanks Tim!

**Pull request merged**
